# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: clone ic2-fabric dependency
        run: git clone https://github.com/yu1745/ic2-fabric.git ../ic2-fabric --depth 1
      - name: clone mc-compose dependency
        run: git clone https://github.com/yu1745/mc-compose.git ../mc-compose --depth 1
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: |
          chmod +x ./gradlew
          chmod +x ../ic2-fabric/gradlew
          chmod +x ../mc-compose/gradlew
      - name: build ic2-fabric dependency
        run: cd ../ic2-fabric && ./gradlew build
      - name: build mc-compose dependency
        run: cd ../mc-compose && ./gradlew build
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
